### ISSUE TITLE
NAs produced by integer overflow

### ISSUE THREAD

**Issue by ColyFu** [huanglikun/BRM#5]
Dear Dr. Huang,

We used BRM for BSA analysis of rice and encountered the attached error. Could you please help find the cause of the error? I can send you the input data if needed. Thank you very much!

Jun

Read global parameters from BRM_conf.txt .
Parameter Design=A
Parameter n1=35
Parameter n2=35
Parameter t=1
Parameter ua=3.65
Parameter UNIT=1000
Parameter DEG=2
Parameter BLK=0.2
Parameter MIN=10
Parameter MINVALID=10
Parameter Result1_File=result/result1.xls
Parameter Result2_File=result/result2.xls

Number of missing data: 25697 
Number of imported chromosomes is 12 .
Data size of 1 is 89153 .
Total blocks in 1: 216356
Number of valid block: 37493 
Error in double(N * M1) : vector size cannot be NA
Calls: run_step1 -> predict -> predict.loess -> predLoess -> double
In addition: Warning message:
In N * M1 : NAs produced by integer overflow
Execution halted

**Comment by huanglikun** [comment]
Thank you for using BRM! I'll try to fix the bug and provide more warnings instead of errors later.
Before the bug was fixed, you could try this approach as follow:
The block size setting for rice is recommended to be 5K to 20K, meaning BLK=5 to BLK=20. Maybe BLK=0.2 for rice is too small. The suitable block size is about a physical distance of 0.1cM.
P.S. BLK=0.2 is a recommended setting for yeast.

**Comment by ColyFu** [comment]
It worked like a charm. Thank you for your prompt reply.
